//! The README's headline example must be what the tool actually prints.
//!
//! A hand-edited example is a small lie, and this project has no standing to tell it. The
//! block is generated by `backcheck demo`, and this test fails the moment the two drift.

use std::process::Command;

#[test]
fn readme_shows_real_demo_output() {
    let exe = env!("CARGO_BIN_EXE_backcheck");
    let out = Command::new(exe)
        .args(["demo", "--no-color"])
        .output()
        .expect("running backcheck demo");
    let printed = String::from_utf8_lossy(&out.stdout);
    let body = printed
        .split("  In that session")
        .next()
        .expect("demo output")
        .trim_end();

    let readme = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/README.md"))
        .expect("reading README.md");

    for line in body.lines().filter(|l| !l.trim().is_empty()) {
        assert!(
            readme.contains(line.trim_end()),
            "README is missing a line the demo prints:\n  {line}\n\
             Regenerate it with: cargo run -- demo --no-color"
        );
    }
}
